language: node_js

node_js:
    - "4"

script:
    - npm i eslint
    - node node_modules/eslint/bin/eslint "lib/ace/**/*.js"
    - npm test

matrix:
    fast_finish: false

cache:
    directories:
        - node_modules

sudo: false
