language: node_js

node_js:
    - "8"

install:
    - cleanup() { find node_modules -regextype posix-extended -iregex '.*((test|example|doc|demo)s?|\.(md)|license|idea|coverage|file.txt)$' -exec rm -rf {} \; || echo $?; };
      install() { npm i && npm i eslint codecov istanbul typescript && cp package.json node_modules/package.json; cleanup; };
      cmp --silent package.json node_modules/package.json || install;

script:
    -   changes=$(git diff --name-only origin/HEAD --no-renames --diff-filter=ACMR);
        if [ "$changes" == "" ]; then
            echo "checking all files";
            node node_modules/eslint/bin/eslint "lib/ace/**/*.js";
        else
            changes=$(echo "$changes" | grep -P '.js$');
            echo "checking $changes";
            if [ "$changes" != "" ]; then
                node node_modules/eslint/bin/eslint $changes;
            fi
        fi
    - node_modules/.bin/istanbul cover lib/ace/test/all.js
    - node_modules/.bin/codecov
    - node_modules/.bin/tsc --noImplicitAny --strict --noUnusedLocals --noImplicitReturns --noUnusedParameters --noImplicitThis ace.d.ts

matrix:
    fast_finish: false

cache:
    directories:
        - node_modules

sudo: false

git:
    depth: 1
    submodules: false
 
branches:
    only:
    - master