<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>scrypt</string>
    <key>scopeName</key>
    <string>source.scrypt</string>
    <key>fileTypes</key>
    <array>
      <string>scrypt</string>
    </array>
    <key>uuid</key>
    <string>d9b8bb5e-b236-11eb-8529-0242ac130003</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.scrypt</string>
            <key>begin</key>
            <string>(/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\*/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scrypt</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.scrypt</string>
            <key>begin</key>
            <string>(\/\/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
          </dict>
        </array>
      </dict>
      <key>filepath</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\")</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\")</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.scrypt</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>string.quoted.double.bytes.scrypt</string>
          </dict>
        </array>
      </dict>
      <key>import</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(import)\s</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.import.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#filepath</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>other-variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>property-variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>parameter-variable</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>primitive-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(bool|int|bytes|PrivKey|PubKey|Sig|Ripemd160|Sha1|Sha256|SigHashType|SigHashPreimage|OpCodeType)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.primitive.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>primitive-arrays</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(bool|int|bytes|PrivKey|PubKey|Sig|Ripemd160|Sha1|Sha256|SigHashType|SigHashPreimage|OpCodeType)\b\s*(?=\[)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.primitive.array.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\s*\[)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numbers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parens</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>auto-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(auto)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.auto.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>all-types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#primitive-types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#auto-types</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([A-Z][_$[:alnum:]]*)\b</string>
            <key>name</key>
            <string>entity.name.type.scrypt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.scrypt</string>
            <key>match</key>
            <string>\b(return|loop|if|else)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.require.scrypt</string>
            <key>match</key>
            <string>\b(require)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.exit.scrypt</string>
            <key>match</key>
            <string>\b(exit)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.auto.scrypt</string>
            <key>match</key>
            <string>\b(auto)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.asm.scrypt</string>
            <key>match</key>
            <string>\b(asm)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.new.scrypt</string>
            <key>match</key>
            <string>\b(new)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.struct.scrypt</string>
            <key>match</key>
            <string>\b(struct)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.type.scrypt</string>
            <key>match</key>
            <string>\b(type)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant-boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#primitive-types</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logic.scrypt</string>
            <key>match</key>
            <string>(==|!=|!(?!=)|&lt;(?!&lt;)|&lt;=|&gt;(?!&gt;)|&gt;=|\&amp;\&amp;|\|\||\:(?!=)|\?)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.scrypt</string>
            <key>match</key>
            <string>\b(\+|\-|\/|\%|\*)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.binary.scrypt</string>
            <key>match</key>
            <string>(\~|\^|\&amp;|\||&lt;&lt;|&gt;&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.scrypt</string>
            <key>match</key>
            <string>(\:?=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.seperator.scrypt</string>
            <key>match</key>
            <string>(\*{3})</string>
          </dict>
        </array>
      </dict>
      <key>constant-boolean</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.scrypt</string>
            <key>match</key>
            <string>\b(true|false)\b</string>
          </dict>
        </array>
      </dict>
      <key>storage-modifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(public|private|static|const)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>contract</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.class.scrypt</string>
            <key>begin</key>
            <string>\b(contract|library)(\s+([_$[:alpha:]][_$[:alnum:]]*))?\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.contract.scrypt</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.contract.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage-modifiers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#contract-body</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>contract-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.class.body.scrypt</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>(?=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#proerties-and-functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>type-alias</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.definition.alias.scrypt</string>
            <key>begin</key>
            <string>\b(type)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.type.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#type-alias-name</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operators</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numbers</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>type-alias-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#numbers</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#properties-reference</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(0[xX][a-fA-F0-9]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.hex.scrypt</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\d+(\.\d+)?)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>bytes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(b'[0-9a-fA-F]*')</string>
            <key>name</key>
            <string>string.quoted.single.bytes.scrypt</string>
          </dict>
        </array>
      </dict>
      <key>special-vars</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.language.this.scrypt</string>
            <key>match</key>
            <string>\b(this)\b</string>
          </dict>
        </array>
      </dict>
      <key>proerties-and-functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#properties</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#static-properties</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.method.scrypt</string>
            <key>begin</key>
            <string>(?=[\w].*\s+)(?=([^=/]|/(?!/))+\()</string>
            <key>end</key>
            <string>(})|(?=;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#contract-constructor</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#contract-function</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>contract-constructor</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.function.scrypt</string>
            <key>begin</key>
            <string>\b(constructor)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parens</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-body</string>
          </dict>
        </array>
      </dict>
      <key>contract-function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.function.scrypt</string>
            <key>begin</key>
            <string>\b(function)\s+([_$[:alpha:]][_$[:alnum:]]*)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.function.scrypt</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#parameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parens</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-return</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-body</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
      <key>function-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.definition.function.scrypt</string>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.method.begin.bracket.curly.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=})</string>
            <key>contentName</key>
            <string>meta.method.body.scrypt</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>function-return</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.method.return-type.scrypt</string>
            <key>begin</key>
            <string>(\:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.semicolon.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\{)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#all-types</string>
                      </dict>
                    </array>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#numbers</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#properties-reference</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#other-variable</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#numbers</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#properties-reference</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\)|,)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parameter-variable</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>global-functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(abs|min|max|within|ripemd160|sha1|sha256|hash160|hash256|checkSig|checkMultiSig|num2bin|pack|unpack|len|reverseBytes|repeat)\s*(\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.math.scrypt</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(PrivKey|PubKey|Sig|Ripemd160|Sha1|Sha256|SigHashType|SigHashPreimage|OpCodeType)\s*(\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.subtypes.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>function-call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#global-functions</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>([_$[:alpha:]][_$[:alnum:]]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#keywords</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>\b([_$[:alpha:]][_$[:alnum:]]*)\b</string>
                    <key>captures</key>
                    <dict>
                      <key>0</key>
                      <dict>
                        <key>name</key>
                        <string>entity.name.function.scrypt</string>
                      </dict>
                    </dict>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.bracket.round.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.bracket.round.scrypt</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.function-call.scrypt</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>new-contract</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(new)\s*([_$[:alpha:]][_$[:alnum:]]*)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.new.scrypt</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                </array>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.new-contract.scrypt</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>method-call</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([_$[:alpha:]][_$[:alnum:]]*)[^\S\n\r]*(\.)[^\S\n\r]*([_$[:alpha:]][_$[:alnum:]]*)[^\S\n\r]*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#special-vars</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.period.scrypt</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.scrypt</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.bracket.round.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.bracket.round.scrypt</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.method-call.scrypt</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>struct</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.definition.struct.scrypt</string>
            <key>begin</key>
            <string>\b(struct)\s*([_$[:alpha:]][_$[:alnum:]]*)\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.struct.scrypt</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.struct.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?\s+([_$[:alpha:]][_$[:alnum:]]*)\s*(;)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#all-types</string>
                      </dict>
                    </array>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#numbers</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#properties-reference</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#other-variable</string>
                      </dict>
                    </array>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>variable.object.property.scrypt</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>std-contracts</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#std-opcodes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#std-sigHash</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.scrypt</string>
            <key>match</key>
            <string>\b(P2PKH|P2PK|Tx|HashPuzzleRipemd160|HashPuzzleSha1|HashPuzzleSha256|HashPuzzleHash160|OpCode|SigHash)\b</string>
          </dict>
        </array>
      </dict>
      <key>variable-decl</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.definition.variable.scrypt</string>
            <key>begin</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?\s+([_$[:alpha:]][_$[:alnum:]]*)\s*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#numbers</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#properties-reference</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#new-contract</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>properties</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?\s+([_$[:alpha:]][_$[:alnum:]]*)\s*(;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#numbers</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#properties-reference</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>meta.definition.property.scrypt variable.object.property.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>static-properties</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#storage-modifiers</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*((\[[\w.]+\])+)?\s+([_$[:alpha:]][_$[:alnum:]]*)\s*(=)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#numbers</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#properties-reference</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>meta.definition.property.scrypt variable.object.property.scrypt</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>properties-reference</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b([_$[:alpha:]][_$[:alnum:]]*)\s*(\.)\s*([_$[:alpha:]][_$[:alnum:]]*)\b(?=[^\(\.])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#all-types</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#other-variable</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.scrypt</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.)\s*([_$[:alpha:]][_$[:alnum:]]*)\b(?=[^\(])</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>asm-block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(asm)\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.asm.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>variable.parameter.asm.scrypt</string>
                <key>match</key>
                <string>\s(\$[_$[:alpha:]][_$[:alnum:]]*)\b</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(OP_PUSHDATA1|OP_PUSHDATA2|OP_PUSHDATA4|OP_0|OP_FALSE|OP_1NEGATE|OP_1|OP_TRUE|OP_2|OP_3|OP_4|OP_5|OP_6|OP_7|OP_8|OP_9|OP_10|OP_11|OP_12|OP_13|OP_14|OP_15|OP_16|OP_1ADD|OP_1SUB|OP_NEGATE|OP_ABS|OP_NOT|OP_0NOTEQUAL|OP_ADD|OP_SUB|OP_MUL|OP_DIV|OP_MOD|OP_LSHIFT|OP_RSHIFT|OP_BOOLAND|OP_BOOLOR|OP_NUMEQUAL|OP_NUMEQUALVERIFY|OP_NUMNOTEQUAL|OP_LESSTHAN|OP_GREATERTHAN|OP_LESSTHANOREQUAL|OP_GREATERTHANOREQUAL|OP_MIN|OP_MAX|OP_WITHIN|OP_CAT|OP_SPLIT|OP_BIN2NUM|OP_NUM2BIN|OP_SIZE|OP_NOP|OP_IF|OP_NOTIF|OP_ELSE|OP_ENDIF|OP_VERIFY|OP_RETURN|OP_TOALTSTACK|OP_FROMALTSTACK|OP_IFDUP|OP_DEPTH|OP_DROP|OP_DUP|OP_NIP|OP_OVER|OP_PICK|OP_ROLL|OP_ROT|OP_SWAP|OP_TUCK|OP_2DROP|OP_2DUP|OP_3DUP|OP_2OVER|OP_2ROT|OP_2SWAP|OP_RIPEMD160|OP_SHA1|OP_SHA256|OP_HASH160|OP_HASH256|OP_CODESEPARATOR|OP_CHECKSIG|OP_CHECKSIGVERIFY|OP_CHECKMULTISIG|OP_CHECKMULTISIGVERIFY|OP_INVERT|OP_AND|OP_OR|OP_XOR|OP_EQUAL|OP_EQUALVERIFY)\b</string>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>name</key>
                        <string>support.other.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_PUSHDATA1|OP_PUSHDATA2|OP_PUSHDATA4)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>constant.language.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_0|OP_FALSE|OP_1NEGATE|OP_1|OP_TRUE|OP_2|OP_3|OP_4|OP_5|OP_6|OP_7|OP_8|OP_9|OP_10|OP_11|OP_12|OP_13|OP_14|OP_15|OP_16)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>support.function.math.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_1ADD|OP_1SUB|OP_NEGATE|OP_ABS|OP_NOT|OP_0NOTEQUAL|OP_ADD|OP_SUB|OP_MUL|OP_DIV|OP_MOD|OP_LSHIFT|OP_RSHIFT|OP_BOOLAND|OP_BOOLOR|OP_NUMEQUAL|OP_NUMEQUALVERIFY|OP_NUMNOTEQUAL|OP_LESSTHAN|OP_GREATERTHAN|OP_LESSTHANOREQUAL|OP_GREATERTHANOREQUAL|OP_MIN|OP_MAX|OP_WITHIN)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>support.function.bytes.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_CAT|OP_SPLIT|OP_BIN2NUM|OP_NUM2BIN|OP_SIZE)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>keyword.control.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_NOP|OP_IF|OP_NOTIF|OP_ELSE|OP_ENDIF|OP_VERIFY|OP_RETURN)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>support.function.stack.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_TOALTSTACK|OP_FROMALTSTACK|OP_IFDUP|OP_DEPTH|OP_DROP|OP_DUP|OP_NIP|OP_OVER|OP_PICK|OP_ROLL|OP_ROT|OP_SWAP|OP_TUCK|OP_2DROP|OP_2DUP|OP_3DUP|OP_2OVER|OP_2ROT|OP_2SWAP)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>support.function.crypto.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_RIPEMD160|OP_SHA1|OP_SHA256|OP_HASH160|OP_HASH256|OP_CODESEPARATOR|OP_CHECKSIG|OP_CHECKSIGVERIFY|OP_CHECKMULTISIG|OP_CHECKMULTISIGVERIFY)\b</string>
                      </dict>
                      <dict>
                        <key>name</key>
                        <string>support.function.logic.opcode.scrypt</string>
                        <key>match</key>
                        <string>\b(OP_INVERT|OP_AND|OP_OR|OP_XOR|OP_EQUAL|OP_EQUALVERIFY)\b</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b([a-fA-F0-9]+)\b</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>constant.numeric.hex.scrypt</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>std-opcodes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(OpCode)\s*(\.)\s*(OP_PUSHDATA1|OP_PUSHDATA2|OP_PUSHDATA4|OP_0|OP_FALSE|OP_1NEGATE|OP_1|OP_TRUE|OP_2|OP_3|OP_4|OP_5|OP_6|OP_7|OP_8|OP_9|OP_10|OP_11|OP_12|OP_13|OP_14|OP_15|OP_16|OP_1ADD|OP_1SUB|OP_NEGATE|OP_ABS|OP_NOT|OP_0NOTEQUAL|OP_ADD|OP_SUB|OP_MUL|OP_DIV|OP_MOD|OP_LSHIFT|OP_RSHIFT|OP_BOOLAND|OP_BOOLOR|OP_NUMEQUAL|OP_NUMEQUALVERIFY|OP_NUMNOTEQUAL|OP_LESSTHAN|OP_GREATERTHAN|OP_LESSTHANOREQUAL|OP_GREATERTHANOREQUAL|OP_MIN|OP_MAX|OP_WITHIN|OP_CAT|OP_SPLIT|OP_BIN2NUM|OP_NUM2BIN|OP_SIZE|OP_NOP|OP_IF|OP_NOTIF|OP_ELSE|OP_ENDIF|OP_VERIFY|OP_RETURN|OP_TOALTSTACK|OP_FROMALTSTACK|OP_IFDUP|OP_DEPTH|OP_DROP|OP_DUP|OP_NIP|OP_OVER|OP_PICK|OP_ROLL|OP_ROT|OP_SWAP|OP_TUCK|OP_2DROP|OP_2DUP|OP_3DUP|OP_2OVER|OP_2ROT|OP_2SWAP|OP_RIPEMD160|OP_SHA1|OP_SHA256|OP_HASH160|OP_HASH256|OP_CODESEPARATOR|OP_CHECKSIG|OP_CHECKSIGVERIFY|OP_CHECKMULTISIG|OP_CHECKMULTISIGVERIFY|OP_INVERT|OP_AND|OP_OR|OP_XOR|OP_EQUAL|OP_EQUALVERIFY)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.scrypt</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.definition.property.scrypt variable.object.property.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>std-sigHash</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(SigHash)\s*(\.)\s*(ANYONECANPAY|ALL|FORKID|NONE|SINGLE)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.scrypt</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>meta.definition.property.scrypt variable.object.property.scrypt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>parens</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.bracket.round.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.bracket.round.scrypt</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.bracket.square.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.bracket.square.scrypt</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.bracket.square.scrypt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.bracket.square.scrypt</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-alias</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#contract</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#std-contracts</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#asm-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#new-contract</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable-decl</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#special-vars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#properties-reference</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#std-contracts</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-call</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bytes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#other-variable</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>