/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

/* This file was autogenerated from  (uuid: ) */
/****************************************************************************************
 * IT MIGHT NOT BE PERFECT ...But it's a good start from an existing *.tmlanguage file. *
 * fileTypes                                                                            *
 ****************************************************************************************/

define(function(require, exports, module) {
"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var cspHighlightRules = function() {
    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

    this.$rules = {
            start: [
                {
                    token: "constant.language.character",
                    regex: /child-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /connect-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /default-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /font-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /frame-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /img-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /manifest-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /media-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/media-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /object-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /script-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /style-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /worker-src/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /base-uri/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /plugin-types/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/plugin-types"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /sandbox/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /disown-opener/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/disown-opener"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /form-action/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /frame-ancestors/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /report-uri/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /report-to/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /upgrade-insecure-requests/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /block-all-mixed-content/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /require-sri-for/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-sri-for"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /reflected-xss/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/reflected-xss"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /referrer/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /policy-uri/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/policy-uri"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /'self'/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /'unsafe-inline'/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /'unsafe-eval'/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /'strict-dynamic'/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src"
                    
                },
                {
                    token: "constant.language.character",
                    regex: /'unsafe-hashed-attributes'/,
                    comment: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src"
                    
                }
            ]
        }
    
    this.normalizeRules();
};

cspHighlightRules.metaData = 


oop.inherits(cspHighlightRules, TextHighlightRules);

exports.cspHighlightRules = cspHighlightRules;
});