/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

/* This file was autogenerated from ./fsl.tmLanguage (uuid: ) */
/****************************************************************************************
 * IT MIGHT NOT BE PERFECT ...But it's a good start from an existing *.tmlanguage file. *
 * fileTypes                                                                            *
 ****************************************************************************************/

define(function(require, exports, module) {
"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var FSLHighlightRules = function() {
    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

    this.$rules = {
        start: [{
            token: "punctuation.definition.comment.mn",
            regex: /\/\*/,
            push: [{
                token: "punctuation.definition.comment.mn",
                regex: /\*\//,
                next: "pop"
            }, {
                defaultToken: "comment.block.fsl"
            }],
            comment: "block comment"
        }, {
            token: "comment.line.fsl",
            regex: /\/\//,
            push: [{
                token: "comment.line.fsl",
                regex: /$/,
                next: "pop"
            }, {
                defaultToken: "comment.line.fsl"
            }],
            comment: "block comment"
        }, {
            token: "entity.name.function",
            regex: /\${/,
            push: [{
                token: "entity.name.function",
                regex: /}/,
                next: "pop"
            }, {
                defaultToken: "keyword.other"
            }],
            comment: "js outcalls"
        }, {
            token: "constant.numeric",
            regex: /[0-9]*\.[0-9]*\.[0-9]*/,
            comment: "semver"
        }, {
            token: "constant.language.fslLanguage",
            regex: /graph_layout\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /machine_name\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /machine_author\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /machine_license\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /machine_comment\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /machine_language\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /machine_version\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /graph_layout\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_init\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_halt\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_end\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_terminate\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_finalize\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_transition\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_action\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_stochastic_action\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_legal\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_main\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_forced\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_validation\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_validation_failure\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_transition_refused\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_forced_transition_refused\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_action_refused\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_enter\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /on_exit\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /start_states\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /end_states\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "constant.language.fslLanguage",
            regex: /fsl_version\s*:/,
            comment: "fsl language tokens"
        }, {
            token: "keyword.control.transition.fslArrow.legal_legal",
            regex: /<->/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.legal_none",
            regex: /<-/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.none_legal",
            regex: /->/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.main_main",
            regex: /<=>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.none_main",
            regex: /=>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.main_none",
            regex: /<=/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.forced_forced",
            regex: /<~>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.none_forced",
            regex: /~>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.forced_none",
            regex: /<~/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.legal_main",
            regex: /<-=>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.main_legal",
            regex: /<=->/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.legal_forced",
            regex: /<-~>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.forced_legal",
            regex: /<~->/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.main_forced",
            regex: /<=~>/,
            comment: "transitions"
        }, {
            token: "keyword.control.transition.fslArrow.forced_main",
            regex: /<~=>/,
            comment: "transitions"
        }, {
            token: "constant.numeric.fslProbability",
            regex: /[0-9]+%/,
            comment: "edge probability annotation"
        }, {
            token: "constant.character.fslAction",
            regex: /\'[^']*\'/,
            comment: "action annotation"
        }, {
            token: "string.quoted.double.fslLabel.doublequoted",
            regex: /\"[^"]*\"/,
            comment: "fsl label annotation"
        }, {
            token: "entity.name.tag.fslLabel.atom",
            regex: /[a-zA-Z0-9_.+&()#@!?,]/,
            comment: "fsl label annotation"
        }]
    };

    this.normalizeRules();
};

FSLHighlightRules.metaData = {
    fileTypes: ["fsl", "fsl_state"],
    name: "FSL",
    scopeName: "source.fsl"
}


oop.inherits(FSLHighlightRules, TextHighlightRules);

exports.FSLHighlightRules = FSLHighlightRules;
});