/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

var oop = require("../lib/oop");
var TextMode = require("./text").Mode;
var DWSHighlightRules = require("./dws_highlight_rules").DWSHighlightRules;
// TODO: pick appropriate fold mode
var FoldMode = require("./folding/coffee").FoldMode;

var Mode = function() {
    this.HighlightRules = DWSHighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, TextMode);

(function() {
       
    this.lineCommentStart = ["--", "//"];
    this.blockComment = [
        {start: "/*", end: "*/"},
        {start: "{", end: "}"}
    ];
    
    this.$id = "ace/mode/dws";
}).call(Mode.prototype);

exports.Mode = Mode;
