/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

    "use strict";

    var oop = require("../lib/oop");
    var TextMode = require("./text").Mode;
    var QmlHighlightRules = require("./qml_highlight_rules").QmlHighlightRules;
    var FoldMode = require("./folding/cstyle").FoldMode;

    var Mode = function() {
        this.HighlightRules = QmlHighlightRules;
        this.foldingRules = new FoldMode();
        this.$behaviour = this.$defaultBehaviour;
    };
    oop.inherits(Mode, TextMode);

    (function() {
        this.lineCommentStart = "//";
        this.blockComment = {start: "/*", end: "*/"};
        this.$quotes = { '"': '"', "'": "'" };
        this.$id = "ace/mode/qml";
    }).call(Mode.prototype);

    exports.Mode = Mode;
