/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

var oop = require("../lib/oop");
var TextMode = require("./text").Mode;
var scryptHighlightRules = require("./scrypt_highlight_rules").scryptHighlightRules;
var FoldMode = require("./folding/cstyle").FoldMode;

var Mode = function () {
    this.HighlightRules = scryptHighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, TextMode);

(function () {
    this.lineCommentStart = "//";
    this.blockComment = {
        start: "/*",
        end: "*/"
    };
    this.$quotes = {
        '"': '"',
        "'": "'"
    };

    this.createWorker = function (session) {

        return null;
    };


    this.$id = "ace/mode/scrypt";
}).call(Mode.prototype);

exports.Mode = Mode;
